version: '3.9'

services:
  postgres:
    container_name: database
    image: postgres:16.0-alpine3.18
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak_db
    ports:
      - "1600:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - local
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    depends_on:
      - "postgres"
    ports:
      - "1601:8080"
    networks:
      - local
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin


networks:
  local:
    name: local
    driver: bridge

volumes:
  postgres:
